name: Hassfest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hassfest:
    name: Home Assistant validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
